name: Fork echo & issue

on:
    fork:

    workflow_run:

jobs:
    first-job:
        runs-on: ubuntu-latest

        steps:

            - name: Trigger echo when a fork occur
              run: echo "fork you !"
            